import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Heart, MapPin, PawPrint, Search, SlidersHorizontal } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { petAge, readPets, SPECIES_NAMES, type Pet } from "@/lib/pets";

export const Route = createFileRoute("/adocao/")({ component: AdoptionPage });

function AdoptionPage() {
  const [pets, setPets] = useState<Pet[]>([]);
  const [query, setQuery] = useState("");
  const [species, setSpecies] = useState("all");
  useEffect(() => setPets(readPets().filter((pet) => pet.adoptionAvailable)), []);
  const availableSpecies = useMemo(() => [...new Set(pets.map((pet) => pet.species))], [pets]);
  const visiblePets = useMemo(() => pets.filter((pet) => {
    const matchesQuery = `${pet.name} ${pet.species} ${pet.breed} ${pet.city} ${pet.description}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"));
    return matchesQuery && (species === "all" || pet.species === species);
  }), [pets, query, species]);

  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-12">
    <header className="mb-10 flex flex-wrap items-center justify-between gap-4"><Link to="/" className="flex items-center gap-3 text-sm font-semibold"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary text-primary-foreground"><PawPrint className="h-5 w-5"/></span>Animal Controller</Link><Link to="/pets/" className="rounded-xl border border-border px-4 py-2.5 text-sm font-semibold transition hover:bg-secondary">Área do tutor</Link></header>
    <section className="relative mb-10 overflow-hidden rounded-3xl border border-border bg-card p-7 sm:p-11"><div className="pointer-events-none absolute -right-12 -top-20 h-72 w-72 rounded-full bg-primary/10 blur-3xl"/><div className="relative max-w-2xl"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.22em] text-primary"><Heart className="h-4 w-4"/>Encontre um novo melhor amigo</p><h1 className="mt-4 font-display text-4xl font-semibold leading-tight sm:text-5xl">Um encontro pode mudar duas vidas<span className="text-primary">.</span></h1><p className="mt-4 max-w-xl text-sm leading-6 text-muted-foreground">Conheça pets que estão esperando por um lar cheio de cuidado. Cada perfil conta um pouquinho de quem eles são.</p><div className="mt-7 flex flex-wrap gap-3"><div className="flex min-w-60 flex-1 items-center gap-2 rounded-xl border border-border bg-background px-4 py-3"><Search className="h-4 w-4 text-muted-foreground"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, cidade..." className="min-w-0 flex-1 bg-transparent text-sm outline-none"/></div><label className="flex items-center gap-2 rounded-xl border border-border bg-background px-3"><SlidersHorizontal className="h-4 w-4 text-muted-foreground"/><select aria-label="Filtrar por espécie" value={species} onChange={(event) => setSpecies(event.target.value)} className="bg-transparent py-3 text-sm outline-none"><option value="all">Todas as espécies</option>{availableSpecies.map((id) => <option key={id} value={id}>{SPECIES_NAMES[id] ?? id}</option>)}</select></label></div></div></section>
    <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Adote com carinho</p><h2 className="mt-2 font-display text-2xl font-semibold">Pets disponíveis <span className="text-sm font-medium text-muted-foreground">{visiblePets.length}</span></h2></div></div>
      {visiblePets.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visiblePets.map((pet) => <Link key={pet.id} to="/adocao/$petId" params={{ petId: pet.id }} className="group overflow-hidden rounded-2xl border border-border bg-card transition hover:-translate-y-1 hover:border-primary/50 hover:shadow-xl hover:shadow-black/10"><div className="relative h-60 overflow-hidden bg-gradient-to-br from-emerald-950 to-slate-800">{pet.photo ? <img src={pet.photo} alt={pet.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/> : <div className="grid h-full place-items-center text-primary/80"><PawPrint className="h-16 w-16"/></div>}<span className="absolute left-4 top-4 rounded-full border border-white/15 bg-black/45 px-3 py-1 text-xs text-white backdrop-blur">{SPECIES_NAMES[pet.species] ?? pet.species}</span><span className="absolute right-4 top-4 rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">À procura de um lar</span></div><div className="p-5"><div className="flex items-start justify-between"><div><h3 className="font-display text-xl font-semibold">{pet.name}</h3><p className="mt-1 text-sm text-muted-foreground">{pet.breed || SPECIES_NAMES[pet.species]}</p></div><span className="grid h-9 w-9 place-items-center rounded-full bg-secondary text-muted-foreground transition group-hover:bg-primary group-hover:text-primary-foreground"><ArrowRight className="h-4 w-4"/></span></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground"><span>{petAge(pet.birthDate)}</span><span>{pet.size || "Porte não informado"}</span><span className="flex items-center gap-1"><MapPin className="h-3.5 w-3.5"/>{pet.city || "Cidade não informada"}</span></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-muted-foreground">{pet.description || "Conheça este pet e descubra se vocês combinam."}</p></div></Link>)}</div> : <div className="rounded-3xl border border-dashed border-border bg-card/40 px-6 py-16 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-primary"><Heart className="h-7 w-7"/></span><h2 className="mt-5 font-display text-xl font-semibold">{pets.length ? "Não encontramos pets com esses filtros" : "Novos encontros estão a caminho"}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-muted-foreground">{pets.length ? "Ajuste sua busca ou escolha outra espécie." : "Ainda não há perfis publicados. Volte em breve para conhecer os pets disponíveis."}</p>{!pets.length && <Link to="/pets/" className="mt-6 inline-flex items-center gap-2 rounded-xl border border-border px-4 py-3 text-sm font-semibold hover:bg-secondary">Sou tutor e quero divulgar um pet<ArrowRight className="h-4 w-4"/></Link>}</div>}
    </section><p className="mt-10 text-center text-xs leading-5 text-muted-foreground">A adoção responsável começa com informação, conversa e cuidado. Combine os detalhes diretamente com o tutor.</p>
  </div></main>;
}
